language: node_js
node_js:
  - "node"
  - "7"
  - "6"

jobs:
  include:
    script: npm build
    script: npm test
    deploy:
      provider: npm
      api_key: $NPM_API_TOKEN
      on:
        tags: true
        skip_cleanup: true
