language: node_js

node_js:
  - 'node'
  - '8'
  - '6'
  
script: 
  - npm test

jobs:
  include:
    - stage: Publish
      node_js: 'node'
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_TOKEN
        skip_cleanup: true
        on:
          tags: true
